spring.datasource.url=jdbc:postgresql://41.59.225.78:5432/ems_db
spring.datasource.username=postgres
spring.datasource.password=NewPass123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


server.port=8080

# HikariCP stable configuration
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.validationTimeout=5000

# IMPORTANT FIXES (this removes your warning)
spring.datasource.hikari.maxLifetime=1700000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.keepaliveTime=300000

# Prevent stale connection reuse
spring.datasource.hikari.connectionTestQuery=SELECT 1

# server.ssl.enabled=true
# server.ssl.key-store=/app/ems-keystore.p12
# server.ssl.key-store-password=ems1234
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=ems-ssl

