spring.datasource.url=jdbc:postgresql://41.59.225.78:5444/ems_db
spring.datasource.username=ems_user
spring.datasource.password=postgr123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


server.port=8080

# server.ssl.enabled=true
# server.ssl.key-store=/app/ems-keystore.p12
# server.ssl.key-store-password=ems1234
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=ems-ssl

